[2025-08-08T10:00:09.698+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-08T10:00:09.790+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: twitter_love_dag.fetch_tweets scheduled__2025-08-08T09:00:00+00:00 [queued]>
[2025-08-08T10:00:09.844+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: twitter_love_dag.fetch_tweets scheduled__2025-08-08T09:00:00+00:00 [queued]>
[2025-08-08T10:00:09.894+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-08-08T10:00:09.984+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_tweets> on 2025-08-08 09:00:00+00:00
[2025-08-08T10:00:10.117+0000] {standard_task_runner.py:63} INFO - Started process 93 to run task
[2025-08-08T10:00:10.158+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'twitter_love_dag', 'fetch_tweets', 'scheduled__2025-08-08T09:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/twitter_love_dag.py', '--cfg-path', '/tmp/tmpf7k36qw_']
[2025-08-08T10:00:10.204+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask fetch_tweets
[2025-08-08T10:00:10.332+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-08-08T10:00:10.548+0000] {task_command.py:426} INFO - Running <TaskInstance: twitter_love_dag.fetch_tweets scheduled__2025-08-08T09:00:00+00:00 [running]> on host ef743f407d39
[2025-08-08T10:00:10.886+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='twitter_love_dag' AIRFLOW_CTX_TASK_ID='fetch_tweets' AIRFLOW_CTX_EXECUTION_DATE='2025-08-08T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-08T09:00:00+00:00'
[2025-08-08T10:00:10.888+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-08T10:00:12.076+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-08T10:00:12.085+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/twitter_love_dag.py", line 33, in fetch_tweets
    tweets = client.search_recent_tweets(
  File "/home/airflow/.local/lib/python3.10/site-packages/tweepy/client.py", line 1276, in search_recent_tweets
    return self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
  File "/home/airflow/.local/lib/python3.10/site-packages/tweepy/client.py", line 98, in request
    raise Unauthorized(response)
tweepy.errors.Unauthorized: 401 Unauthorized
Unauthorized
[2025-08-08T10:00:12.477+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_love_dag, task_id=fetch_tweets, execution_date=20250808T090000, start_date=20250808T100009, end_date=20250808T100012
[2025-08-08T10:00:12.525+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task fetch_tweets (401 Unauthorized
Unauthorized; 93)
[2025-08-08T10:00:12.583+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-08T10:00:12.687+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-08T10:00:12.691+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
